### ISSUE TITLE
Make enforcement of marking generated code optional

### ISSUE THREAD

**Issue by pellared** [dolmen-go/codegen#2]
From https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source:

> To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):

Notice that documentation even says **should** - it is just a recommendation.

The potential issue of generating code with such comments is that a lot of tools (e.g. https://github.com/golangci/golangci-lint) will ignore these files while people may want to have additional checks and refinements than just `gofmt`.

**Comment by dolmen** [comment]
I think that the standard is good as it allows editors and others tools to block humans from editing generated files.

I think that `golangci-lint` ignoring generated files by default is a bad thing for the ecosystem. I would prefer instead to document in this project how to configure `golangci-lint` to lint even generated files. Unfortunately I just discovered that [each linter has its own setting](https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml) for handling generated files, so that doesn't looks easy to do.

Conclusion: This package is opiniated. I will NOT make this *major* feature optional.

**Comment by pellared** [comment]
Here is the main code handling generated files: https://github.com/golangci/golangci-lint/blob/5a668425555cf50b955e458448f9af24440afe57/pkg/result/processors/autogenerated_exclude.go
